# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e4fe3e86ecc4c36d55a388c28fb4da439d7a93078ccbf83a56d33bc24c64222a76d560f17bacac1c76e6f8e0aed5484a398331f150aae3af3dc0fd19c069619

test:
  secret_key_base: 5530d0b75f29527a44d9b58399cc6a39e44951794a5ca7c734ab2e61e4eeaa271d60659066eb8c21cb0974d6450df348fc8bd310740c0c45d7291b4dd2cae861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
